### ISSUE TITLE
How to apply Sincerity API to matching pages automatically?

### ISSUE THREAD

**Issue by andybets** [andybets/steem-sincerity-chrome-extension#1]
Currently the user must click the Sincerity Extension icon each time they wish to re-render a page. I would like to change this to be automatic on matching pages, but to reduce load on the API, it must not run more often than necessary.

This injected script probably needs to bind to some event which signifies that there's been a change of path, and then check that path is a post, but I'm not yet sure how to do this within a Condenser (react) page.

**Comment by shapiroz** [comment]
Hey Andy, 
~~chrome.browserAction.onClicked.addListener(function (tab) {~~
chrome.tabs.onUpdated.addListener(function (tab) {
worked for me.

**Comment by andybets** [comment]
Great, thanks I'll try that.
